// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aavqllytaksomouvsicn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhdnFsbHl0YWtzb21vdXZzaWNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1OTc3NjAsImV4cCI6MjA1NTE3Mzc2MH0.0oPC4WtWDAhJ5rnx1EYVlVe95M5Zn6VP1TIBUc0zVQo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);